import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

// Download markdown content as .md file
export const downloadMarkdown = (content, filename) => {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// Generate and download PDF with logo
export const downloadPDF = async (article, content) => {
  try {
    // Create a temporary container for the PDF content
    const tempContainer = document.createElement('div');
    tempContainer.style.position = 'absolute';
    tempContainer.style.left = '-9999px';
    tempContainer.style.top = '0';
    tempContainer.style.width = '600px'; // Reduced width to match PDF content area
    tempContainer.style.backgroundColor = 'white';
    tempContainer.style.padding = '40px'; // Increased padding for better margins
    tempContainer.style.fontFamily = 'Georgia, serif';
    tempContainer.style.color = '#000000';
    tempContainer.style.lineHeight = '1.6'; // Slightly increased line height
    tempContainer.style.pageBreakInside = 'avoid';
    
    // Add logo
    const logoContainer = document.createElement('div');
    logoContainer.style.textAlign = 'center';
    logoContainer.style.marginBottom = '20px';
    logoContainer.style.paddingBottom = '15px';
    logoContainer.style.borderBottom = '2px solid #fa2132';
    
    const logo = document.createElement('img');
    logo.src = '/FERZLETTERS.svg';
    logo.style.maxWidth = '300px';
    logo.style.height = 'auto';
    logo.style.margin = '0 auto';
    logo.onerror = () => {
      // Fallback if logo doesn't exist
      logoContainer.innerHTML = '<h1 style="color: #fa2132; font-size: 24px; margin: 0;">FERZ</h1>';
    };
    logoContainer.appendChild(logo);
    
    // Add article header
    const headerContainer = document.createElement('div');
    headerContainer.style.marginBottom = '20px';
    headerContainer.style.textAlign = 'center';
    
    const title = document.createElement('h1');
    title.textContent = article.title;
    title.style.fontSize = '24px';
    title.style.fontWeight = 'bold';
    title.style.color = '#000000';
    title.style.marginBottom = '10px';
    title.style.fontFamily = 'Inter, sans-serif';
    
    const description = document.createElement('p');
    description.textContent = article.description;
    description.style.fontSize = '14px';
    description.style.color = '#666666';
    description.style.marginBottom = '15px';
    description.style.fontStyle = 'italic';
    
    const metaInfo = document.createElement('div');
    metaInfo.style.fontSize = '12px';
    metaInfo.style.color = '#666666';
    metaInfo.style.marginBottom = '15px';
    metaInfo.innerHTML = `
      <div style="margin-bottom: 5px;"><strong>Author:</strong> ${article.author}</div>
      <div style="margin-bottom: 5px;"><strong>Published:</strong> ${new Date(article.date).toLocaleDateString()}</div>
      <div style="margin-bottom: 5px;"><strong>Category:</strong> ${article.category}</div>
      <div><strong>Read Time:</strong> ${article.readTime}</div>
    `;
    
    headerContainer.appendChild(title);
    headerContainer.appendChild(description);
    headerContainer.appendChild(metaInfo);
    
    // Process markdown content to HTML
    const processedContent = processMarkdownToHTML(content);
    const contentContainer = document.createElement('div');
    contentContainer.innerHTML = processedContent;
    contentContainer.style.fontSize = '12px';
    contentContainer.style.lineHeight = '1.5';
    contentContainer.style.pageBreakInside = 'auto';
    
    // Add footer
    const footerContainer = document.createElement('div');
    footerContainer.style.marginTop = '30px';
    footerContainer.style.paddingTop = '15px';
    footerContainer.style.borderTop = '1px solid #e0e0e0';
    footerContainer.style.textAlign = 'center';
    footerContainer.style.fontSize = '10px';
    footerContainer.style.color = '#666666';
    footerContainer.innerHTML = `
      <div>Generated by FERZ Consulting</div>
      <div>Visit us at ferzconsulting.com</div>
    `;
    
    // Assemble the content
    tempContainer.appendChild(logoContainer);
    tempContainer.appendChild(headerContainer);
    tempContainer.appendChild(contentContainer);
    tempContainer.appendChild(footerContainer);
    
    document.body.appendChild(tempContainer);
    
    // Generate PDF with proper page margins and spacing
    const canvas = await html2canvas(tempContainer, {
      scale: 1.5,
      useCORS: true,
      allowTaint: true,
      backgroundColor: '#ffffff',
      height: tempContainer.scrollHeight,
      width: tempContainer.scrollWidth
    });
    
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    
    // Set proper page margins (20mm on all sides)
    const pageMargin = 20;
    const imgWidth = 210 - (pageMargin * 2); // 170mm content width
    const pageHeight = 295 - (pageMargin * 2); // 255mm content height
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    
    let position = 0;
    
    // Add first page with proper margins
    pdf.addImage(imgData, 'PNG', pageMargin, pageMargin + position, imgWidth, imgHeight);
    heightLeft -= pageHeight;
    
    // Add additional pages if needed with proper margins
    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', pageMargin, pageMargin + position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }
    
    // Clean up
    document.body.removeChild(tempContainer);
    
    // Download PDF
    pdf.save(`${article.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`);
    
  } catch (error) {
    console.error('Error generating PDF:', error);
    alert('Error generating PDF. Please try again.');
  }
};

// Process markdown content to proper HTML
const processMarkdownToHTML = (markdown) => {
  let html = markdown;
  
  // Convert headings - left aligned, reduced spacing
  html = html.replace(/^### (.*$)/gim, '<h3 style="font-size: 16px; font-weight: bold; color: #000000; margin: 12px 0 6px 0; font-family: Inter, sans-serif; text-align: left;">$1</h3>');
  html = html.replace(/^## (.*$)/gim, '<h2 style="font-size: 20px; font-weight: bold; color: #fa2132; margin: 16px 0 8px 0; font-family: Inter, sans-serif; text-align: left;">$1</h2>');
  html = html.replace(/^# (.*$)/gim, '<h1 style="font-size: 24px; font-weight: bold; color: #000000; margin: 20px 0 10px 0; font-family: Inter, sans-serif; text-align: left;">$1</h1>');
  
  // Convert bold text
  html = html.replace(/\*\*(.*?)\*\*/g, '<strong style="font-weight: bold;">$1</strong>');
  
  // Convert italic text
  html = html.replace(/\*(.*?)\*/g, '<em style="font-style: italic;">$1</em>');
  
  // Convert code blocks - reduced padding
  html = html.replace(/```([\s\S]*?)```/g, '<pre style="background: #f8f9fa; padding: 10px; border-radius: 3px; border: 1px solid #e9ecef; overflow-x: auto; font-family: Courier New, monospace; font-size: 11px; margin: 8px 0; page-break-inside: avoid;"><code>$1</code></pre>');
  
  // Convert inline code
  html = html.replace(/`([^`]+)`/g, '<code style="background: #f1f3f4; padding: 2px 4px; border-radius: 2px; font-family: Courier New, monospace; font-size: 11px;">$1</code>');
  
  // Convert blockquotes - reduced padding
  html = html.replace(/^> (.*$)/gim, '<blockquote style="border-left: 3px solid #fa2132; padding-left: 12px; margin: 8px 0; color: #666666; font-style: italic; background: #f8f9fa; padding: 10px; border-radius: 0 3px 3px 0; page-break-inside: avoid;">$1</blockquote>');
  
  // Convert lists - reduced spacing
  html = html.replace(/^\* (.*$)/gim, '<li style="margin: 2px 0;">$1</li>');
  html = html.replace(/^- (.*$)/gim, '<li style="margin: 2px 0;">$1</li>');
  html = html.replace(/^(\d+)\. (.*$)/gim, '<li style="margin: 2px 0;">$2</li>');
  
  // Wrap consecutive list items in ul/ol - reduced spacing
  html = html.replace(/(<li[^>]*>.*<\/li>)/g, (match, p1, offset, string) => {
    const before = string.substring(0, offset);
    const after = string.substring(offset + match.length);
    const beforeMatch = before.match(/(<li[^>]*>.*<\/li>)$/);
    const afterMatch = after.match(/^(<li[^>]*>.*<\/li>)/);
    
    if (!beforeMatch && afterMatch) {
      return '<ul style="margin: 8px 0; padding-left: 20px; page-break-inside: avoid;">' + match;
    } else if (beforeMatch && !afterMatch) {
      return match + '</ul>';
    } else if (!beforeMatch && !afterMatch) {
      return '<ul style="margin: 8px 0; padding-left: 20px; page-break-inside: avoid;">' + match + '</ul>';
    }
    return match;
  });
  
  // Convert line breaks
  html = html.replace(/\n/g, '<br>');
  
  // Convert paragraphs - reduced spacing
  html = html.replace(/(<br>){2,}/g, '</p><p style="margin: 8px 0;">');
  html = '<p style="margin: 8px 0;">' + html + '</p>';
  
  return html;
};

// Download executive summary as PDF
export const downloadExecutiveSummary = async (article) => {
  try {
    const pdf = new jsPDF('p', 'mm', 'a4');
    
    // Add logo
    const logoImg = new Image();
    logoImg.crossOrigin = 'anonymous';
    logoImg.onload = () => {
      // Center the logo horizontally with proper margins
      const logoWidth = 60;
      const logoHeight = 20;
      const pageWidth = 210;
      const pageMargin = 20;
      const logoX = (pageWidth - logoWidth) / 2;
      pdf.addImage(logoImg, 'PNG', logoX, pageMargin + 5, logoWidth, logoHeight);
      generateSummaryContent(pdf, article);
    };
    logoImg.onerror = () => {
      // Fallback if logo doesn't load
      pdf.setFontSize(20);
      pdf.setTextColor(250, 33, 50);
      pdf.text('FERZ', 105, 30, { align: 'center' });
      generateSummaryContent(pdf, article);
    };
    logoImg.src = '/FERZLETTERS.svg';
  } catch (error) {
    console.error('Error generating executive summary:', error);
    alert('Error generating executive summary. Please try again.');
  }
};

const generateSummaryContent = (pdf, article) => {
  // Set proper page margins (20mm on all sides)
  const pageMargin = 20;
  const contentWidth = 170; // 210mm - 40mm margins
  
  // Set up fonts and colors
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(16);
  pdf.setTextColor(0, 0, 0);
  
  // Title with proper spacing from top
  pdf.text(article.title, pageMargin, pageMargin + 20);
  
  // Description
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(12);
  pdf.setTextColor(100, 100, 100);
  
  const descriptionLines = pdf.splitTextToSize(article.description, contentWidth);
  pdf.text(descriptionLines, pageMargin, pageMargin + 40);
  
  // Key information
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(14);
  pdf.setTextColor(0, 0, 0);
  pdf.text('Key Information', pageMargin, pageMargin + 80);
  
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(11);
  pdf.setTextColor(100, 100, 100);
  
  const info = [
    `Author: ${article.author}`,
    `Published: ${new Date(article.date).toLocaleDateString()}`,
    `Category: ${article.category}`,
    `Read Time: ${article.readTime}`,
    `Tags: ${article.tags.join(', ')}`
  ];
  
  let yPosition = pageMargin + 90;
  info.forEach(item => {
    pdf.text(item, pageMargin, yPosition);
    yPosition += 6;
  });
  
  // Executive Summary content
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(14);
  pdf.setTextColor(0, 0, 0);
  pdf.text('Executive Summary', pageMargin, pageMargin + 130);
  
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(11);
  pdf.setTextColor(100, 100, 100);
  
  const summaryText = `This article explores ${article.category.toLowerCase()} and provides insights into ${article.description.toLowerCase()}. The content is designed for ${article.author} and offers valuable perspectives on the topic.`;
  
  const summaryLines = pdf.splitTextToSize(summaryText, contentWidth);
  pdf.text(summaryLines, pageMargin, pageMargin + 140);
  
  // Footer with proper spacing from bottom
  pdf.setFontSize(8);
  pdf.setTextColor(150, 150, 150);
  pdf.text('Generated by FERZ Consulting', pageMargin, 280 - pageMargin);
  pdf.text('Visit us at ferzconsulting.com', pageMargin, 285 - pageMargin);
  
  // Download
  pdf.save(`${article.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_executive_summary.pdf`);
};
